name: Demo autocode
description: Demo autocode (app.autocode.run)
author:
  name: Chema Fernández Varela
  email: jmfvarela@gmail.com
  url: 'http://www.twitter.com/jmfvarela'
copyright: 2015 Chema Fernández Varela
